name: net_mock
description: A Dart package designed to simplify HTTP request mocking in your tests.
version: 1.0.0
repository: https://github.com/KwabenBerko/net_mock

environment:
  sdk: ^3.4.3

dependencies:
  http: ^1.2.2
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
